#!/bin/bash

cell_width=6
cell_height=14
background=black

PropsCacheDir="${XDG_CACHE_HOME:-$HOME/.cache}/vifm-sixel-preview"

if [ -r "$PROPSFILE" ]; then
  . "$PROPSFILE"
else
  for pfile in "$PropsCacheDir"/*; do
    if [ -r "$pfile" ]; then
      . "$pfile"
      break
    fi
  done
  unset pfile
fi

###########
# runtime #
###########

CacheDimN=256
CacheDimL=512
CacheDimX=1024
CacheDim=""

get_max() {
  if [ "$1" -gt "$2" ]; then
    echo "$1"
  else
    echo "$2"
  fi
}

get_min() {
  if [ "$1" -lt "$2" ]; then
    echo "$1"
  else
    echo "$2"
  fi
}

get_thumbnail_name () {
    filepath=$(realpath "$1")
    perl -MURI::file -MDigest::MD5=md5_hex \
        -e 'printf "%s.png\n", md5_hex(URI::file->new(shift))' "$filepath"
}

CacheBaseDir="${XDG_CACHE_HOME:-$HOME/.cache}/thumbnails"
CacheN="${CacheBaseDir}/large"
CacheL="${CacheBaseDir}/x-large"
CacheX="${CacheBaseDir}/xx-large"
UseCacheDir=""

[ -d "$HOME/.cache/vifm" ] || mkdir -p "$HOME/.cache/vifm"

# $1 action
action="$1"
# $2 panel width
# $3 panel height
panel_width=$2
panel_height=$3
width=$((panel_width*cell_width))
height=$((panel_height*cell_height))

MaxDispDim=$(get_max "$width" "$height")

if [ "$MaxDispDim" -lt "$CacheDimN" ]; then
  CacheDim="$CacheDimN"
  UseCacheDir="$CacheN"
elif [ "$MaxDispDim" -lt "$CacheDimL" ]; then
  CacheDim="$CacheDimL"
  UseCacheDir="$CacheL"
else
  CacheDim="$CacheDimX"
  UseCacheDir="$CacheX"
fi

CxC="${CacheDim}x${CacheDim}"

# absolute image path
file="$PWD/$4"

CacheFile=$(get_thumbnail_name "$file")

CachePath="${UseCacheDir}/${CacheFile}"

# Type: int
# value: 0
_true=0
# Type: int
# value: 1
_false=1

check_cache() {
    # check if cache file exists
    [ ! -f "$1" ] && return "$_false"

    # Check if original file is newer than cache
    [ "$file" -nt "$1" ] && return "$_false"

    return "$_true"
}

cleanup() {
    printf '\33[s\33[5A\33[2K\33[u'
    clear
    exit 0
}

# recieves image with height
image() {
    montage "$1" -background "$background" -geometry "${2}x${3}" sixel:-
  }

case "$action" in
  "clear")
    cleanup
    ;;
  "draw")
    case "$(realpath "$PWD")" in
      *"$CacheBaseDir"*)
        image "$file" "$width" "$height"
        ;;
      *)
        if ! check_cache "$CachePath"; then
          convert "$file"'[0]' -resize "$CxC" "$CachePath" 2> /dev/null
        fi
        image "$CachePath" "$width" "$height"
        ;;
    esac
    ;;
  "video")
    if ! check_cache "$CachePath"; then
      ffmpegthumbnailer -i "$file" -o "$CachePath" -s "$CacheDim"  -q 5 2> /dev/null
    fi
    image "$CachePath" "$width" "$height"
    ;;
  "epub")
    epub-thumbnailer "$file" "$CachePath" "$CacheDim" 2> /dev/null
    image "$CachePath" "$width" "$height"
    ;;
  "pdf")
    if ! check_cache "$CachePath"; then
      pdftoppm -png -f 1 -singlefile -scale-to "$CacheDim" "$file" "$CachePath" 2> /dev/null
    fi
    image "$CachePath" "$width" "$height"
    ;;
  "audio")
    if ! check_cache "$CachePath"; then
      ffmpeg -i "$file" "$CachePath" -y >/dev/null
    fi
    image "$CachePath" "$width" "$height"
    ;;
  "font")
    if ! check_cache "$CachePath"; then
      fontpreview --size "$CxC" -i "$file" -o "$CachePath" 2> /dev/null
    fi
    image "$CachePath" "$width" "$height"
    ;;
  *)
esac
